[package]
name = "datafusion-functions-json"
version = "0.45.0"
edition = "2021"
description = "JSON functions for DataFusion"
readme = "README.md"
license = "Apache-2.0"
keywords = ["datafusion", "JSON", "SQL"]
categories = ["database-implementations", "parsing"]
repository = "https://github.com/datafusion-contrib/datafusion-functions-json/"
rust-version = "1.81.0"

[dependencies]
datafusion = { git = "https://github.com/apache/datafusion.git", rev = "a9fb58c", default-features = false }
jiter = "0.8" # Jitter has a dependency on pyo3, which needs to match the version used in DataFusion
paste = "1"
log = "0.4"

[dev-dependencies]
datafusion = { git = "https://github.com/apache/datafusion.git", rev = "a9fb58c", default-features = false, features = ["nested_expressions"] }
codspeed-criterion-compat = "2.6"
criterion = "0.5.1"
clap = "4"
tokio = { version = "1.38", features = ["full"] }

[lints.clippy]
dbg_macro = "deny"
print_stdout = "deny"

# in general, we lint against the pedantic group, but we will whitelist
# certain lints which we don't want to enforce (for now)
pedantic = { level = "deny", priority = -1 }

[[bench]]
name = "main"
harness = false
